version: 2
updates:
  - package-ecosystem: nuget
    directory: "/HHS-course-5-2024_11_30/ORM mapping and manipulating data/HHS_ORM/HHS_ORM"
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      minor-and-patch:
        update-types: [minor, patch]
